# Generated by Django 5.2 on 2025-04-09 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_wallet_user_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='transaction_type',
            field=models.CharField(choices=[('Inflow', 'Inflow'), ('Outflow', 'Outflow')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
