# Generated by Django 5.2 on 2025-04-09 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_wallet_transaction_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='transaction_type',
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('Inflow', 'Inflow'), ('Outflow', 'Outflow')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
