# Generated by Django 5.2 on 2025-04-10 08:58
from datetime import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_transaction_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='day',
            field=models.DateField(default=datetime.today()),
            preserve_default=False,
        ),
    ]
