# Generated by Django 5.2 on 2025-04-10 22:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_transaction_day'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='transaction_type',
            new_name='flow',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='day',
            field=models.DateField(blank=True, default=datetime.datetime(2025, 4, 10, 22, 7, 37, 969695), null=True),
        ),
    ]
