# Generated by Django 5.2 on 2025-04-23 21:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_rename_transaction_type_transaction_flow_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='day',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='flow',
            field=models.IntegerField(default=1),
        ),
    ]
