# Generated by Django 5.2.1 on 2025-06-08 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_patients'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patients',
            old_name='second_name',
            new_name='last_name',
        ),
    ]
