# Generated by Django 5.2.1 on 2025-06-08 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_patients_height_patients_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='next_appointment',
            field=models.DateField(blank=True, null=True),
        ),
    ]
