# Generated by Django 5.2.1 on 2025-06-08 19:40

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_patients_next_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='last_appointment',
            field=models.DateField(default=datetime.datetime(2025, 6, 8, 0, 0)),
        ),
        migrations.CreateModel(
            name='ProgressiveVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('visit_type', models.CharField(max_length=100)),
                ('pay', models.BooleanField(default=False)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_progressive_visits', to='core.patients')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progressive_visits', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
