# Generated by Django 5.2.1 on 2025-06-08 19:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_patients_last_appointment_progressivevisit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progressivevisit',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 6, 8, 0, 0)),
        ),
    ]
