# Generated by Django 5.2.1 on 2025-06-08 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_progressivevisit_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progressivevisit',
            name='height',
        ),
    ]
