# Generated by Django 5.2.1 on 2025-06-08 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_remove_progressivevisit_height'),
    ]

    operations = [
        migrations.AddField(
            model_name='progressivevisit',
            name='BMI',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
