# Generated by Django 5.2.1 on 2025-06-08 22:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_progressivevisit_bmi'),
    ]

    operations = [
        migrations.AddField(
            model_name='patients',
            name='first_appointment',
            field=models.DateField(blank=True, default=datetime.datetime(2025, 6, 8, 0, 0), null=True),
        ),
    ]
