# Generated by Django 5.2.1 on 2025-06-08 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_patients_first_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='progressivevisit',
            name='next_appointment',
            field=models.DateField(blank=True, null=True),
        ),
    ]
